site_name: practice_django

docs_dir: "docs"

nav:
  - index: index.md
  - pip install: pip.md
  - settings: settings.md
  - Dev: dev.md
  - Blog: blog/models.md

theme:
  name: material

dev_addr: 127.0.0.1:8200

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages

collapse_single_pages: true

site_author: Ruslan Dovhanych
